apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo The app is running! && sleep 10']
  
  restartPolicy: Never
  
  initContainers:  - name: my-init-container-1
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo my-init-container-1 start; sleep 3 ;echo my-init-container-1 complete;']  - name: my-init-container-2
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo my-init-container-2 start; sleep 3;echo my-init-container-2 complete;']    - name: my-init-container-3
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo my-init-container-3 start; sleep 3;echo my-init-container-3 complete;']    - name: my-init-container-4
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo my-init-container-4 start; sleep 3;echo my-init-container-4 complete;']
